# questions.py

all_questions = [
    # ==========================================
    # LEVEL 1: EASY (20 Questions)
    # ==========================================
    # Number Sense
    {"id": 101, "difficulty": "Level 1: Easy", "category": "Number Sense & Operations", "question": r"Evaluate: $15 - (-4) + 3 \times 2$", "options": ["25", "13", "11", "26"], "answer": "25", "solution": r"$3 \times 2 = 6$. $15 + 4 + 6 = 25$."},
    {"id": 102, "difficulty": "Level 1: Easy", "category": "Number Sense & Operations", "question": r"Convert $\frac{3}{5}$ to a percentage.", "options": ["30%", "60%", "35%", "50%"], "answer": "60%", "solution": r"$\frac{3 \times 20}{5 \times 20} = \frac{60}{100} = 60\%$."},
    {"id": 103, "difficulty": "Level 1: Easy", "category": "Number Sense & Operations", "question": r"Evaluate: $4^3$", "options": ["12", "16", "64", "256"], "answer": "64", "solution": r"$4 \times 4 \times 4 = 64$."},
    {"id": 104, "difficulty": "Level 1: Easy", "category": "Number Sense & Operations", "question": r"What is 20% of 80?", "options": ["16", "20", "8", "160"], "answer": "16", "solution": r"$0.20 \times 80 = 16$."},
    {"id": 105, "difficulty": "Level 1: Easy", "category": "Number Sense & Operations", "question": r"Simplify: $\frac{18}{24}$", "options": ["3/4", "2/3", "4/5", "6/8"], "answer": "3/4", "solution": r"Divide top and bottom by 6: $\frac{3}{4}$."},
    # Pre-Algebra
    {"id": 106, "difficulty": "Level 1: Easy", "category": "Pre-Algebra & Equations", "question": r"Solve for x: $4x + 7 = 23$", "options": ["x = 3", "x = 4", "x = 5", "x = 6"], "answer": "x = 4", "solution": r"$4x = 16$, so $x = 4$."},
    {"id": 107, "difficulty": "Level 1: Easy", "category": "Pre-Algebra & Equations", "question": r"If $y = 3x - 2$, find y when $x = 5$.", "options": ["13", "15", "17", "11"], "answer": "13", "solution": r"$y = 3(5) - 2 = 15 - 2 = 13$."},
    {"id": 108, "difficulty": "Level 1: Easy", "category": "Pre-Algebra & Equations", "question": r"Simplify: $3(a + 4) - 2a$", "options": ["a + 12", "5a + 12", "a + 4", "5a + 4"], "answer": "a + 12", "solution": r"$3a + 12 - 2a = a + 12$."},
    {"id": 109, "difficulty": "Level 1: Easy", "category": "Pre-Algebra & Equations", "question": r"Solve: $x - (-5) = 12$", "options": ["7", "17", "-7", "12"], "answer": "7", "solution": r"$x + 5 = 12$, subtract 5 to get $x = 7$."},
    {"id": 110, "difficulty": "Level 1: Easy", "category": "Pre-Algebra & Equations", "question": r"Combine like terms: $4x + 5y - 2x + 3y$", "options": ["2x + 8y", "6x + 8y", "2x + 2y", "8xy"], "answer": "2x + 8y", "solution": r"$(4x - 2x) + (5y + 3y) = 2x + 8y$."},
    # Geometry
    {"id": 111, "difficulty": "Level 1: Easy", "category": "Geometry & Data", "question": r"Find the area of a triangle with base 10 and height 6.", "options": ["60", "30", "16", "120"], "answer": "30", "solution": r"$Area = \frac{1}{2}bh = \frac{1}{2}(10)(6) = 30$."},
    {"id": 112, "difficulty": "Level 1: Easy", "category": "Geometry & Data", "question": r"What is the perimeter of a rectangle with length 8 and width 3?", "options": ["24", "11", "22", "16"], "answer": "22", "solution": r"$P = 2l + 2w = 2(8) + 2(3) = 16 + 6 = 22$."},
    {"id": 113, "difficulty": "Level 1: Easy", "category": "Geometry & Data", "question": r"Angles in a triangle add up to what?", "options": ["90°", "180°", "360°", "270°"], "answer": "180°", "solution": r"The interior angles of any triangle always sum to 180°."},
    {"id": 114, "difficulty": "Level 1: Easy", "category": "Geometry & Data", "question": r"Find the missing angle in a triangle if two angles are 40° and 60°.", "options": ["100°", "90°", "80°", "180°"], "answer": "80°", "solution": r"$180 - (40 + 60) = 180 - 100 = 80^\circ$."},
    {"id": 115, "difficulty": "Level 1: Easy", "category": "Geometry & Data", "question": r"What is the mean of 4, 8, and 12?", "options": ["8", "24", "6", "10"], "answer": "8", "solution": r"$(4 + 8 + 12) / 3 = 24 / 3 = 8$."},
    # Number Theory & Probability
    {"id": 116, "difficulty": "Level 1: Easy", "category": "Number Theory & Probability", "question": r"What is the Greatest Common Factor (GCF) of 12 and 18?", "options": ["2", "3", "6", "36"], "answer": "6", "solution": r"Factors of 12: 1,2,3,4,6,12. Factors of 18: 1,2,3,6,9,18. GCF is 6."},
    {"id": 117, "difficulty": "Level 1: Easy", "category": "Number Theory & Probability", "question": r"Probability of rolling an even number on a 6-sided die?", "options": ["1/6", "1/3", "1/2", "2/3"], "answer": "1/2", "solution": r"Even numbers are 2, 4, 6. So 3 out of 6 total options. $3/6 = 1/2$."},
    {"id": 118, "difficulty": "Level 1: Easy", "category": "Number Theory & Probability", "question": r"Which of these is a prime number?", "options": ["9", "15", "17", "21"], "answer": "17", "solution": r"17 is only divisible by 1 and itself."},
    {"id": 119, "difficulty": "Level 1: Easy", "category": "Number Theory & Probability", "question": r"Least Common Multiple (LCM) of 4 and 6?", "options": ["10", "12", "24", "2"], "answer": "12", "solution": r"Multiples of 4: 4,8,12,16. Multiples of 6: 6,12,18. LCM is 12."},
    {"id": 120, "difficulty": "Level 1: Easy", "category": "Number Theory & Probability", "question": r"Probability of flipping a coin and getting heads twice in a row?", "options": ["1/2", "1/4", "1/3", "1/8"], "answer": "1/4", "solution": r"$\frac{1}{2} \times \frac{1}{2} = \frac{1}{4}$."},

    # ==========================================
    # LEVEL 2: INTERMEDIATE (20 Questions)
    # ==========================================
    # Number Sense
    {"id": 201, "difficulty": "Level 2: Intermediate", "category": "Number Sense & Operations", "question": r"Evaluate: $\left( -\frac{2}{3} \right)^2 \div \frac{4}{9} - (-3)^3$", "options": ["28", "-26", "26", "-28"], "answer": "28", "solution": r"Square fraction: $4/9$. Divide: $4/9 \div 4/9 = 1$. Exponent: $(-3)^3 = -27$. Subtract: $1 - (-27) = 28$."},
    {"id": 202, "difficulty": "Level 2: Intermediate", "category": "Number Sense & Operations", "question": r"A store marks up a $40 item by 25%. Then applies a 10% discount. Final price?", "options": ["$45", "$42.50", "$46", "$50"], "answer": "$45", "solution": r"$25\%$ of $\$40$ is $\$10$, new price $\$50$. $10\%$ discount on $\$50$ is $\$5$. Final is $\$45$."},
    {"id": 203, "difficulty": "Level 2: Intermediate", "category": "Number Sense & Operations", "question": r"$(3.2 \times 10^4) \times (5 \times 10^3)$ in scientific notation?", "options": [r"$1.6 \times 10^8$", r"$16 \times 10^7$", r"$1.6 \times 10^7$", r"$8.2 \times 10^7$"], "answer": r"$1.6 \times 10^8$", "solution": r"$3.2 \times 5 = 16$. $10^4 \times 10^3 = 10^7$. $16 \times 10^7 = 1.6 \times 10^8$."},
    {"id": 204, "difficulty": "Level 2: Intermediate", "category": "Number Sense & Operations", "question": r"Simplify: $\frac{\frac{1}{2} + \frac{1}{3}}{\frac{1}{4}}$", "options": ["10/3", "5/12", "12/5", "3/10"], "answer": "10/3", "solution": r"Top: $3/6 + 2/6 = 5/6$. Divide: $5/6 \times 4/1 = 20/6 = 10/3$."},
    {"id": 205, "difficulty": "Level 2: Intermediate", "category": "Number Sense & Operations", "question": r"Light A flashes every 18s, Light B every 24s. When do they flash together again?", "options": ["72s", "36s", "144s", "48s"], "answer": "72s", "solution": r"LCM of 18 and 24 is 72."},
    # Pre-Algebra
    {"id": 206, "difficulty": "Level 2: Intermediate", "category": "Pre-Algebra & Equations", "question": r"Solve for x: $\frac{1}{2}(4x - 6) = 3x - 11$", "options": ["x = 8", "x = 4", "x = -8", "x = 14"], "answer": "x = 8", "solution": r"$2x - 3 = 3x - 11$. Subtract $2x$: $-3 = x - 11$. Add 11: $x = 8$."},
    {"id": 207, "difficulty": "Level 2: Intermediate", "category": "Pre-Algebra & Equations", "question": r"Solve: $-3(x - 4) \leq 15$", "options": [r"$x \geq -1$", r"$x \leq -1$", r"$x \geq 9$", r"$x \leq 9$"], "answer": r"$x \geq -1$", "solution": r"Divide by -3 and flip sign: $x - 4 \geq -5$. Add 4: $x \geq -1$."},
    {"id": 208, "difficulty": "Level 2: Intermediate", "category": "Pre-Algebra & Equations", "question": r"Solve system: $2x + y = 10$ and $x - y = 2$", "options": ["x = 4, y = 2", "x = 2, y = 4", "x = 6, y = -2", "x = 3, y = 1"], "answer": "x = 4, y = 2", "solution": r"Add equations: $3x = 12 \rightarrow x = 4$. Substitute: $4 - y = 2 \rightarrow y = 2$."},
    {"id": 209, "difficulty": "Level 2: Intermediate", "category": "Pre-Algebra & Equations", "question": r"Sum of three consecutive even integers is 84. What is the largest?", "options": ["30", "28", "32", "26"], "answer": "30", "solution": r"$x + (x+2) + (x+4) = 84 \rightarrow 3x + 6 = 84 \rightarrow 3x = 78 \rightarrow x = 26$. Largest is $26 + 4 = 30$."},
    {"id": 210, "difficulty": "Level 2: Intermediate", "category": "Pre-Algebra & Equations", "question": r"If $f(x) = -2x^2 + 5x - 3$, find $f(-2)$.", "options": ["-21", "-5", "-13", "9"], "answer": "-21", "solution": r"$-2(-2)^2 + 5(-2) - 3 = -2(4) - 10 - 3 = -8 - 10 - 3 = -21$."},
    # Geometry
    {"id": 211, "difficulty": "Level 2: Intermediate", "category": "Geometry & Data", "question": r"Diagonal of a rectangle with length 12m and width 5m?", "options": ["13m", "17m", "10.9m", "14m"], "answer": "13m", "solution": r"$5^2 + 12^2 = c^2 \rightarrow 25 + 144 = c^2 \rightarrow 169 = c^2 \rightarrow c = 13$."},
    {"id": 212, "difficulty": "Level 2: Intermediate", "category": "Geometry & Data", "question": r"Volume of solid cylinder (r=3, h=10)?", "options": [r"$90\pi$", r"$30\pi$", r"$60\pi$", r"$180\pi$"], "answer": r"$90\pi$", "solution": r"$V = \pi r^2 h = \pi(3^2)(10) = 90\pi$."},
    {"id": 213, "difficulty": "Level 2: Intermediate", "category": "Geometry & Data", "question": r"Parallel lines transversal. Alternate interior angles: $(3x - 15)^\circ$ and $(2x + 10)^\circ$. Find x.", "options": ["x = 25", "x = 5", "x = 35", "x = 15"], "answer": "x = 25", "solution": r"$3x - 15 = 2x + 10 \rightarrow x = 25$."},
    {"id": 214, "difficulty": "Level 2: Intermediate", "category": "Geometry & Data", "question": r"Scores: 82, 86, 90. What fourth score is needed for an 88 mean?", "options": ["94", "92", "96", "88"], "answer": "94", "solution": r"$88 \times 4 = 352$. $352 - (82+86+90) = 352 - 258 = 94$."},
    {"id": 215, "difficulty": "Level 2: Intermediate", "category": "Geometry & Data", "question": r"Area of a circle with diameter 14 cm?", "options": [r"$49\pi$", r"$14\pi$", r"$196\pi$", r"$7\pi$"], "answer": r"$49\pi$", "solution": r"Radius is 7. $Area = \pi r^2 = \pi(7^2) = 49\pi$."},
    # Number Theory & Probability
    {"id": 216, "difficulty": "Level 2: Intermediate", "category": "Number Theory & Probability", "question": r"Bag has 4 red, 6 blue. Draw 2 without replacement. Probability both red?", "options": ["2/15", "4/25", "1/5", "8/45"], "answer": "2/15", "solution": r"$(4/10) \times (3/9) = 12/90 = 2/15$."},
    {"id": 217, "difficulty": "Level 2: Intermediate", "category": "Number Theory & Probability", "question": r"How many positive integer divisors does 120 have?", "options": ["16", "12", "14", "18"], "answer": "16", "solution": r"$120 = 2^3 \times 3^1 \times 5^1$. Divisors = $(3+1)(1+1)(1+1) = 16$."},
    {"id": 218, "difficulty": "Level 2: Intermediate", "category": "Number Theory & Probability", "question": r"Units digit of $7^{45}$?", "options": ["7", "9", "3", "1"], "answer": "7", "solution": r"Cycle of 7 is 7,9,3,1. $45 \div 4 = 11$ R $1$. Remainder 1 means 1st in cycle, which is 7."},
    {"id": 219, "difficulty": "Level 2: Intermediate", "category": "Number Theory & Probability", "question": r"Greatest number of identical boxes using 84 red, 126 blue, 210 black pens?", "options": ["42", "21", "14", "6"], "answer": "42", "solution": r"GCD of 84, 126, 210 is 42."},
    {"id": 220, "difficulty": "Level 2: Intermediate", "category": "Number Theory & Probability", "question": r"Using A, B, C, D, E. How many 3-letter arrangements without repeats?", "options": ["60", "10", "15", "120"], "answer": "60", "solution": r"$5 \times 4 \times 3 = 60$."},

    # ==========================================
    # LEVEL 3: DIFFICULT (20 Questions)
    # ==========================================
    # Number Sense
    {"id": 301, "difficulty": "Level 3: Difficult", "category": "Number Sense & Operations", "question": r"Rationalize denominator: $\frac{\sqrt{3} + \sqrt{2}}{\sqrt{3} - \sqrt{2}}$", "options": [r"$5 + 2\sqrt{6}$", r"$5 - 2\sqrt{6}$", r"$1$", r"$5$"], "answer": r"$5 + 2\sqrt{6}$", "solution": r"Multiply by conjugate: $(\sqrt{3} + \sqrt{2})^2 / (3 - 2) = 3 + 2\sqrt{6} + 2 = 5 + 2\sqrt{6}$."},
    {"id": 302, "difficulty": "Level 3: Difficult", "category": "Number Sense & Operations", "question": r"Solve for x: $8^{x-1} = 16^{2x+3}$", "options": ["-3", "-15/5", "-3/5", "-15/4"], "answer": "-3", "solution": r"$(2^3)^{x-1} = (2^4)^{2x+3} \rightarrow 3x - 3 = 8x + 12 \rightarrow -15 = 5x \rightarrow x = -3$."},
    {"id": 303, "difficulty": "Level 3: Difficult", "category": "Number Sense & Operations", "question": r"Simplify: $\sqrt{75} + \sqrt{48}$", "options": [r"$9\sqrt{3}$", r"$12\sqrt{3}$", r"$8\sqrt{3}$", r"$\sqrt{123}$"], "answer": r"$9\sqrt{3}$", "solution": r"$5\sqrt{3} + 4\sqrt{3} = 9\sqrt{3}$."},
    {"id": 304, "difficulty": "Level 3: Difficult", "category": "Number Sense & Operations", "question": r"Logarithm: Evaluate $\log_2(32)$", "options": ["5", "4", "6", "16"], "answer": "5", "solution": r"$2^5 = 32$, therefore the log base 2 of 32 is 5."},
    {"id": 305, "difficulty": "Level 3: Difficult", "category": "Number Sense & Operations", "question": r"Sum of infinite geometric series: $1 + 1/2 + 1/4 + 1/8 ...$", "options": ["2", "1.5", "Infinity", "4"], "answer": "2", "solution": r"$S = a / (1 - r) = 1 / (1 - 0.5) = 1 / 0.5 = 2$."},
    # Pre-Algebra
    {"id": 306, "difficulty": "Level 3: Difficult", "category": "Pre-Algebra & Equations", "question": r"If $x + \frac{1}{x} = 5$, find $x^2 + \frac{1}{x^2}$", "options": ["23", "25", "27", "10"], "answer": "23", "solution": r"$(x + \frac{1}{x})^2 = x^2 + 2 + \frac{1}{x^2} = 25$. Subtract 2 to get 23."},
    {"id": 307, "difficulty": "Level 3: Difficult", "category": "Pre-Algebra & Equations", "question": r"Solve system: $x^2 + y^2 = 25$ and $xy = 12$. Find positive $(x+y)$", "options": ["7", "5", "12", "14"], "answer": "7", "solution": r"$(x+y)^2 = x^2 + y^2 + 2xy = 25 + 2(12) = 49$. Square root is 7."},
    {"id": 308, "difficulty": "Level 3: Difficult", "category": "Pre-Algebra & Equations", "question": r"Roots of $x^2 - 5x + 6 = 0$?", "options": ["2, 3", "-2, -3", "1, 6", "-1, -6"], "answer": "2, 3", "solution": r"Factors into $(x-2)(x-3) = 0$."},
    {"id": 309, "difficulty": "Level 3: Difficult", "category": "Pre-Algebra & Equations", "question": r"What is the vertex of the parabola $y = x^2 - 4x + 3$?", "options": ["(2, -1)", "(-2, 1)", "(4, 3)", "(0, 3)"], "answer": "(2, -1)", "solution": r"x-coord = $-b/2a = 4/2 = 2$. Plug in 2: $y = 2^2 - 4(2) + 3 = 4 - 8 + 3 = -1$."},
    {"id": 310, "difficulty": "Level 3: Difficult", "category": "Pre-Algebra & Equations", "question": r"Find the domain of $f(x) = \frac{1}{\sqrt{x - 3}}$", "options": [r"$x > 3$", r"$x \geq 3$", r"$x \neq 3$", "All real numbers"], "answer": r"$x > 3$", "solution": r"Denominator cannot be zero or negative. So $x - 3 > 0 \rightarrow x > 3$."},
    # Geometry
    {"id": 311, "difficulty": "Level 3: Difficult", "category": "Geometry & Data", "question": r"Regular hexagon inscribed in circle radius 10. Area?", "options": [r"$150\sqrt{3}$", r"$300$", r"$100\sqrt{3}$", r"$600$"], "answer": r"$150\sqrt{3}$", "solution": r"6 equilateral triangles of side 10. $6 \times (100\sqrt{3}/4) = 150\sqrt{3}$."},
    {"id": 312, "difficulty": "Level 3: Difficult", "category": "Geometry & Data", "question": r"Triangle vertices: A(1, 2), B(5, 6), C(9, 2). Area?", "options": ["16", "32", "8", "24"], "answer": "16", "solution": r"Base AC length is 8. Height from B(5,6) down to y=2 is 4. Area = $0.5 \times 8 \times 4 = 16$."},
    {"id": 313, "difficulty": "Level 3: Difficult", "category": "Geometry & Data", "question": r"Sphere inscribed in a cube. Ratio of Sphere Vol to Cube Vol?", "options": [r"$\pi/6$", r"$\pi/4$", r"$2\pi/3$", r"$1/2$"], "answer": r"$\pi/6$", "solution": r"Cube vol = $(2r)^3 = 8r^3$. Sphere vol = $(4/3)\pi r^3$. Ratio = $(4/3)\pi / 8 = \pi / 6$."},
    {"id": 314, "difficulty": "Level 3: Difficult", "category": "Geometry & Data", "question": r"Length of a 60° arc in a circle of radius 6?", "options": [r"$2\pi$", r"$4\pi$", r"$\pi$", r"$6\pi$"], "answer": r"$2\pi$", "solution": r"Circumference is $12\pi$. 60° is $1/6$ of the circle. $(1/6) \times 12\pi = 2\pi$."},
    {"id": 315, "difficulty": "Level 3: Difficult", "category": "Geometry & Data", "question": r"Distance between points (-2, 4) and (4, -4)?", "options": ["10", "14", "8", "100"], "answer": "10", "solution": r"$\sqrt{(4 - -2)^2 + (-4 - 4)^2} = \sqrt{6^2 + (-8)^2} = \sqrt{36 + 64} = \sqrt{100} = 10$."},
    # Number Theory & Probability
    {"id": 316, "difficulty": "Level 3: Difficult", "category": "Number Theory & Probability", "question": r"Remainder when $2^{2023}$ is divided by 7?", "options": ["2", "1", "4", "3"], "answer": "2", "solution": r"Powers of 2 mod 7 cycle: 2, 4, 1. $2023 \div 3 = 674$ R $1$. Remainder 1 means 1st in cycle: 2."},
    {"id": 317, "difficulty": "Level 3: Difficult", "category": "Number Theory & Probability", "question": r"Five friends sit in a circle. How many arrangements?", "options": ["24", "120", "60", "12"], "answer": "24", "solution": r"Circular permutation formula is $(n-1)!$. $(5-1)! = 4! = 24$."},
    {"id": 318, "difficulty": "Level 3: Difficult", "category": "Number Theory & Probability", "question": r"How many zeroes at the end of 50!?", "options": ["12", "10", "15", "5"], "answer": "12", "solution": r"Count factors of 5. $50/5 = 10$. $50/25 = 2$. $10 + 2 = 12$."},
    {"id": 319, "difficulty": "Level 3: Difficult", "category": "Number Theory & Probability", "question": r"Two dice rolled. Probability sum is a prime number?", "options": ["5/12", "7/18", "1/3", "1/4"], "answer": "5/12", "solution": r"Primes sums (2,3,5,7,11) happen 15 times out of 36. $15/36 = 5/12$."},
    {"id": 320, "difficulty": "Level 3: Difficult", "category": "Number Theory & Probability", "question": r"Choose 3 students from a class of 10. How many combinations?", "options": ["120", "720", "30", "1000"], "answer": "120", "solution": r"10 Choose 3 = $10! / (3! \times 7!) = (10 \times 9 \times 8) / 6 = 120$."}
]
